
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG } from '@/config/supabase';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_CONFIG.url, SUPABASE_CONFIG.anonKey);

// Default restaurant ID to use throughout the application
export const DEFAULT_RESTAURANT_ID = "d2d5278d-8df1-4819-87a0-f23b519e3f2a";

// Helper functions for common operations
export const supabaseOperations = {
  // Test connection
  async testConnection() {
    try {
      console.log('Testing Supabase connection...');
      const { data, error } = await supabase.from('Restaurant').select('id').limit(1);
      console.log('Connection test result:', { data, error });
      return { success: !error, error };
    } catch (error) {
      console.error('Connection test failed:', error);
      return { success: false, error };
    }
  },

  // Get restaurants
  async getRestaurants() {
    try {
      console.log('Getting restaurants...');
      const { data, error } = await supabase
        .from('Restaurant')
        .select('*')
        .order('createdAt', { ascending: false });
      
      console.log('Restaurants result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching restaurants:', error);
      return { data: null, error };
    }
  },

  // Get categories
  async getCategories() {
    try {
      console.log('Getting categories...');
      const { data, error } = await supabase
        .from('MenuCategory')
        .select('*, Restaurant(name)')
        .order('name', { ascending: true });
      
      console.log('Categories result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching categories:', error);
      return { data: null, error };
    }
  },

  // Get products
  async getProducts() {
    try {
      console.log('Getting products...');
      const { data, error } = await supabase
        .from('Product')
        .select('*, MenuCategory(name), Restaurant(name)')
        .order('createdAt', { ascending: false });
      
      console.log('Products result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching products:', error);
      return { data: null, error };
    }
  },

  // Get orders
  async getOrders() {
    try {
      console.log('Getting orders...');
      const { data, error } = await supabase
        .from('Order')
        .select('*, OrderProduct(*, Product(name, price)), Restaurant(name)')
        .order('createdAt', { ascending: false });
      
      console.log('Orders result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching orders:', error);
      return { data: null, error };
    }
  },

  // Get accounts receivable
  async getAccountsReceivable() {
    try {
      console.log('Getting accounts receivable...');
      const { data, error } = await supabase
        .from('AccountsReceivable')
        .select('*, Restaurant(name)')
        .order('createdAt', { ascending: false });
      
      console.log('Accounts receivable result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching accounts receivable:', error);
      return { data: null, error };
    }
  },

  // Get accounts payable
  async getAccountsPayable() {
    try {
      console.log('Getting accounts payable...');
      const { data, error } = await supabase
        .from('AccountsPayable')
        .select('*, Restaurant(name)')
        .order('createdAt', { ascending: false });
      
      console.log('Accounts payable result:', { data, error });
      return { data, error };
    } catch (error) {
      console.error('Error fetching accounts payable:', error);
      return { data: null, error };
    }
  }
};
