
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ep-black-flower-a49ozmbq-pooler.us-east-1.aws.neon.tech";
const SUPABASE_PUBLISHABLE_KEY = "npg_fIkicl0p5Xob";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

